name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine wheel coveralls
          pip install -e .[all]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh

      - name: Build package
        if: ${{ success() && github.event_name == 'release' && matrix.python-version == '3.6'  }}
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package
        if: ${{ success() && github.event_name == 'release' && matrix.python-version == '3.6'  }}
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
