name: Build and release

on:
  push:
    branches: [master]
    tags:
      - "*"
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
          fetch-depth: 0

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine wheel coveralls
          pip install -e .[all]
      - name: Show python dependencies
        run: |
          pip freeze
      - name: Run tests
        run: |
          ./run-tests.sh
      - name: Build package
        if: ${{ success() && github.event_name == 'push' && matrix.python-version == '3.6'  }}
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        if: ${{ success() && github.event_name == 'push' && matrix.python-version == '3.6'  }}
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
